### ISSUE TITLE
中文readme中说明欠缺

### ISSUE THREAD

**Issue by StarCompute** [mkdreams/MDword#6]
在英文说明中说了
_Add annotations or use “${value/}” to the template. Please note that there is a “/” at the end._
但是中文说明中
_给母版“temple.docx”添加批注_
建议修正文档!

**Comment by StarCompute** [comment]
补充说明一下,这个项目很好,对于需要在php下生成word文件的来说非常方便,感谢.
加油!

**Comment by mkdreams** [comment]
fixed
