### ISSUE TITLE
在linux和windows下对于换行的处理有问题

### ISSUE THREAD

**Issue by StarCompute** [mkdreams/MDword#7]
我用了PHP_EOL来处理换行，在windows下生成的word文档正常，在centos下就换行不成功了。代码和模板都是一样的。

**Comment by mkdreams** [comment]
贴下代码呢？

**Comment by StarCompute** [comment]
大概的代码是
$str=str_ireplace('</p>',PHP_EOL,$str);
$WordProcessor->setValue('breaklaw_type',$str);
因为$str 来自于网页端的输入，当把内容放入word的时候，在我本地windows环境下生产的word对于p标记的处理正常，但是centos就不正常了。
我知道两个平台有\r \n 之类的兼容问题，但是php_eol本身就是为了解决这个。

当然我目前采取了笨办法解决了这个问题。

顺便给一个建议：网页端传入的内容很多是html格式，传入到word中应该考虑如何兼容。

**Comment by StarCompute** [comment]
上面的代码应该是 `$str=str_ireplace('</p>',PHP_EOL,$str);`

**Comment by mkdreams** [comment]
> 上面的代码应该是 `$str=str_ireplace('</p>',PHP_EOL,$str);`

换行可以用此[demo](https://github.com/mkdreams/MDword/blob/main/tests/samples/clone/index.php)中的“MDWORD_BREAK”：

```
->bindValue('content',['content'],'item',function($value) {
    $valueArr = explode('<br/>', $value);
    $texts = [];
    foreach($valueArr as $text) {
        $texts[] = ['type'=>MDWORD_TEXT,'text'=>$text];
        $texts[] = ['type'=>MDWORD_BREAK,'text'=>2];
    }
    
    return $texts;
})
;
```

**Comment by StarCompute** [comment]
我其实自己就是这么处理的。
function ConvertPForWord($str){
    $contents=[];
    $conds=explode('</p>',$str);
    $_br_break=['text'=>1,'type'=>MDWORD_BREAK];
    foreach($conds as $c){
        $contents[]=['text'=>'  '.trim(strip_tags($c)).'','type'=>MDWORD_TEXT];
        $contents[]=$_br_break;
    }
    return $contents;
}
只是很多人其实不知道这么处理
